inherit_gem:
  jpalumickas-rubocop-config:
    - "config/rubocop.yml"

AllCops:
  TargetRubyVersion: 2.1
  Include:
    - '**/Rakefile'
    - '**/Gemfile'

Style/DoubleNegation:
  Exclude:
    - 'lib/mailerlite/utils.rb'
