AllCops:
  TargetRubyVersion: 2.0
  Include:
    - '**/Rakefile'
    - '**/Gemfile'

Style/Documentation:
  Enabled: false

Style/AlignParameters:
  Enabled: true
  EnforcedStyle: with_fixed_indentation

Style/MultilineOperationIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/MultilineMethodCallIndentation:
  Enabled: true
  EnforcedStyle: indented

Style/CaseIndentation:
  Enabled: true
  EnforcedStyle: end

Lint/EndAlignment:
  Enabled: true
  EnforcedStyleAlignWith: variable

Style/FrozenStringLiteralComment:
  Enabled: false

Style/DoubleNegation:
  Exclude:
    - 'lib/mailerlite/utils.rb'

Metrics/BlockLength:
  ExcludedMethods:
    - 'describe'
