sudo: false

before_install:
  - gem install bundler

bundler_args: --without development

after_success:
  - bundle exec codeclimate-test-reporter

language: ruby

rvm:
  - 2.0.0
  - 2.1.0
  - 2.2.0
  - 2.3.0
  - 2.4.0
  - ruby-head

matrix:
  allow_failures:
    - rvm: ruby-head
